name: FBCB_env
channels:
  - conda-forge
dependencies:
  - pandas=2.3.3
  - pip=25.3
  - python=3.14.2
  - xlrd=2.0.2
  - pip:
    - colour==0.1.5
    - et_xmlfile==2.0.0
    - openpyxl==3.1.5
    - styleframe==4.2
